[package]
name = "rile-pages"
version = "0.1.0"
edition = "2024"

[features]
default = ["index"]
harfbuzz = ["rile/harfbuzz"]
# Indexes sorted by locale (icu_collator).
index = ["dep:icu_collator", "dep:icu_locale"]

[dependencies]
rile = { path = "../rile", default-features = false }
cassowary = "0.3"
icu_collator = { version = "2.3.1", optional = true }
icu_locale = { version = "2.3.1", optional = true }
