[package]
name = "sile-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
harfbuzz = ["dep:harfbuzz-sys"]

[dependencies]
ttf-parser = "0.25"
fontdb = "0.22"
rustybuzz = "0.20"
self_cell = "1"
unicode-bidi = "0.3"
harfbuzz-sys = { version = "0.6", default-features = false, optional = true }
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.13.3"
hayagriva = "0.10.1"
icu_segmenter = "2"
