[package]
name = "sile-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
harfbuzz = ["dep:harfbuzz-sys"]

[dependencies]
ttf-parser = "0.25"
fontdb = "0.22"
rustybuzz = "0.20"
unicode-bidi = "0.3"
cassowary = "0.3"
pdf-writer = "0.12"
subsetter = "0.2"
miniz_oxide = "0.8"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
harfbuzz-sys = { version = "0.6", default-features = false, optional = true }
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.13.3"
icu_collator = "2.3.1"
icu_locale = "2.3.1"
hayagriva = "0.10.1"
